apiVersion: v1
kind: Service
metadata:
  name: rails-example-app-web
spec:
  selector:
    app: rails-example-app
    tier: web
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 3000
